<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Daseraf\Debug\Model\Collector\PluginCollector $collector */
$collector = $block->getCollector();
$pluginsWithoutTime = !((int)$collector->getBeforePluginsExecutionTime() && (int)$collector->getAroundPluginsExecutionTime() && (int)$collector->getAfterPluginsExecutionTime());
?>
<div>
    <h2><?= $block->escapeHtml(__('Plugins')) ?></h2>
</div>
<?php if ($pluginsWithoutTime): ?>
<div>
    <h5><?= $block->escapeHtml(__('Plugins have no runtime. This happens if the structure of interceptor generation is changed by some module.')); ?></h5>
</div>
<?php endif; ?>

<?php if (!$collector->hasPlugins()): ?>
    <div class="empty">
        <p><?= $block->escapeHtml(__('No plugins have been processed.')) ?></p>
    </div>
<?php else: ?>
    <div class="sf-tabs">
        <div class="tab">
            <h3 class="tab-title">
                <?= $block->escapeHtml(__('BEFORE')) ?>
                <?php if (!$pluginsWithoutTime): ?>
                    <span><?= $block->escapeHtml(__('in')); ?> <?= /* @noEscape */ $collector->getBeforePluginsExecutionTime(); ?> ms</span>
                <?php endif; ?>
                <span class="badge">Count: <?= /* @noEscape */ $collector->getBeforePluginsCount(); ?></span>
            </h3>
            <div class="tab-content">
                <table class="auto">
                    <?php foreach ($collector->getBeforePlugins() as $type => $plugins): ?>
                        <thead>
                        <tr>
                            <th>
                                <?= /* @noEscape */$type; ?>
                                <?php if (!$pluginsWithoutTime): ?>
                                    <?= $block->escapeHtml(__('in')); ?>
                                    <?= $collector->getTypePluginsExecutionTime($type, 1) ?> ms
                                <?php endif; ?>
                            </th>
                            <th><?= $block->escapeHtml(__('Name')) ?></th>
                            <th><?= $block->escapeHtml(__('Sort order')) ?></th>
                            <th><?= $block->escapeHtml(__('Execution Count')) ?></th>
                            <?php if (!$pluginsWithoutTime): ?>
                                <th><?= $block->escapeHtml(__('Total Execution Time')) ?></th>
                            <?php endif; ?>
                        </tr>
                        </thead>
                        <tbody>
                        <?php /** @var \Daseraf\Debug\Model\ValueObject\Plugin $plugin */ ?>
                        <?php foreach ($plugins as $plugin): ?>
                            <tr>
                                <td><?= /* @noEscape */ $plugin->getClass(); ?>::<?= /* @noEscape */ $plugin->getMethod(); ?></td>
                                <td><?= /* @noEscape */ $plugin->getName(); ?></td>
                                <td class="text-center"><?= /* @noEscape */ $plugin->getSortOrder(); ?></td>
                                <td class="text-center"><?= /* @noEscape */ $plugin->getExecutionCount(); ?></td>
                                <?php if (!$pluginsWithoutTime): ?>
                                    <td class="text-center"><?= /* @noEscape */ $collector->formatTime($plugin->getExecutionTime()); ?> ms</td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
        <div class="tab">
            <h3 class="tab-title">
                <?= $block->escapeHtml(__('AROUND')) ?>
                <?php if (!$pluginsWithoutTime): ?>
                    <span><?= $block->escapeHtml(__('in')); ?> <?= /* @noEscape */ $collector->getAroundPluginsExecutionTime(); ?> ms</span>
                <?php endif; ?>
                <span class="badge">Count: <?= /* @noEscape */ $collector->getAroundPluginsCount() ?></span>
            </h3>
            <div class="tab-content">
                <table class="auto">
                    <?php foreach ($collector->getAroundPlugins() as $type => $plugins): ?>
                        <thead>
                        <tr>
                            <th>
                                <?= /* @noEscape */$type; ?>
                                <?php if (!$pluginsWithoutTime): ?>
                                    <?= $block->escapeHtml(__('in')); ?>
                                    <?= $collector->getTypePluginsExecutionTime($type, 2) ?> ms
                                <?php endif; ?>
                            </th>
                            <th><?= $block->escapeHtml(__('Name')) ?></th>
                            <th><?= $block->escapeHtml(__('Sort order')) ?></th>
                            <th><?= $block->escapeHtml(__('Execution Count')) ?></th>
                            <?php if (!$pluginsWithoutTime): ?>
                                <th><?= $block->escapeHtml(__('Total Execution Time')) ?></th>
                            <?php endif; ?>
                        </tr>
                        </thead>
                        <tbody>
                        <?php /** @var \Daseraf\Debug\Model\ValueObject\Plugin $plugin */ ?>
                        <?php foreach ($plugins as $plugin): ?>
                            <tr>
                                <td><?= /* @noEscape */ $plugin->getClass(); ?>::<?= /* @noEscape */ $plugin->getMethod(); ?></td>
                                <td><?= /* @noEscape */ $plugin->getName(); ?></td>
                                <td class="text-center"><?= /* @noEscape */ $plugin->getSortOrder(); ?></td>
                                <td class="text-center"><?= /* @noEscape */ $plugin->getExecutionCount(); ?></td>
                                <?php if (!$pluginsWithoutTime): ?>
                                    <td class="text-center"><?= /* @noEscape */ $collector->formatTime($plugin->getExecutionTime()); ?> ms</td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
        <div class="tab">
            <h3 class="tab-title">
                <?= $block->escapeHtml(__('AFTER')) ?>
                <?php if (!$pluginsWithoutTime): ?>
                    <span><?= $block->escapeHtml(__('in')); ?> <?= /* @noEscape */ $collector->getAfterPluginsExecutionTime(); ?> ms</span>
                <?php endif; ?>
                <span class="badge">Count: <?= /* @noEscape */ $collector->getAfterPluginsCount() ?></span>
            </h3>
            <div class="tab-content">
                <table class="auto">
                    <?php foreach ($collector->getAfterPlugins() as $type => $plugins): ?>
                        <thead>
                        <tr>
                            <th>
                                <?= /* @noEscape */$type; ?>
                                <?php if (!$pluginsWithoutTime): ?>
                                    <?= $block->escapeHtml(__('in')); ?>
                                    <?= $collector->getTypePluginsExecutionTime($type, 4) ?> ms
                                <?php endif; ?>
                            </th>
                            <th><?= $block->escapeHtml(__('Name')) ?></th>
                            <th><?= $block->escapeHtml(__('Sort order')) ?></th>
                            <th><?= $block->escapeHtml(__('Execution Count')) ?></th>
                            <?php if (!$pluginsWithoutTime): ?>
                                <th><?= $block->escapeHtml(__('Total Execution Time')) ?></th>
                            <?php endif; ?>
                        </tr>
                        </thead>
                        <tbody>
                        <?php /** @var \Daseraf\Debug\Model\ValueObject\Plugin $plugin */ ?>
                        <?php foreach ($plugins as $plugin): ?>
                            <tr>
                                <td><?= /* @noEscape */ $plugin->getClass(); ?>::<?= /* @noEscape */ $plugin->getMethod(); ?></td>
                                <td><?= /* @noEscape */ $plugin->getName(); ?></td>
                                <td class="text-center"><?= /* @noEscape */ $plugin->getSortOrder(); ?></td>
                                <td class="text-center"><?= /* @noEscape */ $plugin->getExecutionCount(); ?></td>
                                <?php if (!$pluginsWithoutTime): ?>
                                    <td class="text-center"><?= /* @noEscape */ $collector->formatTime($plugin->getExecutionTime()); ?> ms</td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>
