<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var \Daseraf\Debug\Model\View\Menu $viewModel */ ?>
<?php $viewModel = $block->getViewModel(); ?>

<?php if ($viewModel->isActive($block->getCollectorName())): ?>
    <?php /** @var \Daseraf\Debug\Model\Collector\EventCollector $collector */ ?>
    <?php $collector = $viewModel->getCollector($block->getCollectorName()); ?>
    <li class="request<?= $viewModel->isCurrentPanel($block->getCollectorName()) ? ' selected' : '' ?>">
        <a href="<?= $block->escapeUrl($viewModel->getProfilerUrl($block->getCollectorName())); ?>">
            <span class="label label-status-<?= /* @noEscape */ $collector->getStatus() ?>">
                <span class="icon">
                    <img src="<?= /* @noEscape */ $block->getViewFileUrl('Daseraf_Debug::images/collector/event.svg'); ?>"
                         alt="<?= $block->escapeHtmlAttr(__('Events')); ?>"/>
                </span>
                <strong><?= $block->escapeHtml(__('Events')); ?></strong>
                <span class="count">
                    <span><?= /* @noEscape */ $collector->getObserversCount() ?></span>
                </span>
            </span>
        </a>
    </li>
<?php endif; ?>
