<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Zend_Db_Profiler_Query $query */
$query = $block->getQuery();
?>
<?= /* @noEscape */ $block->getHighlightedQuery(); ?>
<?php if (!empty($query->getQueryParams())) : ?>
    <div>
        <strong class="font-normal text-small"><?= $block->escapeHtml(__('Parameters')) ?></strong>:
        <?= /* @noEscape */ $block->getVarRenderer()->create(['variable' => $query->getQueryParams()])->render(); ?>
    </div>
<?php endif; ?>
<!--<div class="text-small font-normal">-->
<!--    <a href="#" class="sf-toggle link-inverse"-->
<!--       data-toggle-selector="#formatted-query---><?php //= /* @noEscape */ $block->getUniqId() ?><!--"-->
<!--       data-toggle-alt-content="--><?php //= $block->escapeHtml(__('Hide formatted query')) ?><!--">-->
<!--        --><?php //= $block->escapeHtml(__('View formatted query')) ?>
<!--    </a>-->
<!--    <a href="#" class="sf-toggle link-inverse"-->
<!--       data-toggle-selector="#original-query---><?php //= /* @noEscape */ $block->getUniqId() ?><!--"-->
<!--       data-toggle-alt-content="--><?php //= $block->escapeHtml(__('Hide runnable query')) ?><!--">-->
<!--        --><?php //= $block->escapeHtml(__('View runnable query')) ?>
<!--    </a>-->
<!--</div>-->
<!--<div id="formatted-query---><?php //= /* @noEscape */ $block->getUniqId() ?><!--" class="sql-runnable hidden">-->
<!--    --><?php //= /* @noEscape */ $block->getFormattedQuery(); ?>
<!--</div>-->
<!--<div id="original-query---><?php //= /* @noEscape */ $block->getUniqId() ?><!--" class="sql-runnable hidden">-->
<!--    --><?php //= /* @noEscape */ $block->getRunnableQuery(); ?>
<!--</div>-->
