<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var \ClawRock\Debug\Model\View\Toolbar $vm */ ?>
<?php $vm = $block->getViewModel(); ?>
<?php $token = $vm->getToken(); ?>

<div id="sfToolbarClearer-<?= /* @noEscape */ $token; ?>" class="sf-toolbar-clearer"></div>
<div id="sfToolbarMainContent-<?= /* @noEscape */ $token; ?>" class="sf-toolbarreset clear-fix" data-no-turbolink>
    <?php /** @var \Magento\Framework\View\Element\Template $collectorBlock */ ?>
    <?php foreach ($vm->getCollectorBlocks() as $collectorBlock): ?>
        <?= $collectorBlock->toHtml(); ?>
    <?php endforeach; ?>
    <a href="#" class="hide-button" id="sfToolbarHideButton-<?= /* @noEscape */ $token; ?>" title="<?= $block->escapeHtml(__('Close Toolbar')) ?>" tabindex="-1" accesskey="D">
        <img src="<?= /* @noEscape */ $block->getViewFileUrl('ClawRock_Debug::images/icon/close.svg'); ?>" alt="<?= $block->escapeHtml(__('Close')) ?>">
    </a>
</div>
